---
- name: Deploy Dear Lavion App
  hosts: dearlavion-app_{{ env }}
  gather_facts: yes

  vars:
    run_auth: "{{ target in ['auth', 'all'] }}"
    run_core: "{{ target in ['core', 'all'] }}"
    run_web_ui: "{{ target in ['web-ui', 'all'] }}"
    run_redis: "{{ target in ['redis', 'all'] }}"
    run_nginx: "{{ target in ['nginx2', 'all'] }}"
    renew_cert: "{{ target in ['certificate', 'all'] }}"
    run_kafka: "{{ target in ['kafka', 'all'] }}"
    run_notification: "{{ target in ['notification', 'all'] }}"

  pre_tasks:
    - name: Setup system dependencies
      include_role:
        name: common

    - name: Setup docker network
      include_role:
        name: docker_network

  tasks:
    - include_role:
        name: auth
      when: run_auth

    - include_role:
        name: core
      when: run_core

    - include_role:
        name: web_ui
      when: run_web_ui

    - include_role:
        name: redis
      when: run_redis

    - include_role:
        name: nginx2
      when: run_nginx

    - include_role:
        name: certificate
      when: renew_cert

    - include_role:
        name: kafka
      when: run_kafka

    - include_role:
        name: notification
      when: run_notification

  post_tasks:
    # ----------------------------
    # 🔄 Reload nginx AFTER service redeploy
    # ----------------------------
    - name: Reload nginx after service redeploy
      become: true
      command: docker exec dearlavion-nginx nginx -s reload
      ignore_errors: true
      when: run_nginx == false

    - name: Final sanity check
      debug:
        msg: >
          🎉 Deployment completed successfully
          target={{ target }},
          env={{ env }},
          host={{ inventory_hostname }}