# Docker network
dearlavion_network: "dearlavion-net"

# NGINx
nginx_http_port: 80
nginx_https_port: 443

# UI Ports
web_ui_port: 80

# Service Ports
gateway_internal_port: 8080
auth_port: 8081
core_port: 8082
notification_port: 8083
media_port: 8084

# Kafka
akhq_port: 9000

# Image Server
minio_internal_s3_api_port: 9000
minio_internal_web_console_port: 9001
minio_server_url: "s3.dearlavion.site"
minio_browser_url: "console-s3.dearlavion.site"

# NGINX SSL
server_names:
  - dearlavion.site
  - s3.dearlavion.site
  - console-s3.dearlavion.site

renew_cert: false
