project_name: n8n
project_path: "{{ playbook_dir }}/../n8n"
compose_file: "{{ project_path }}/docker-compose.yml"
env_file: "{{ project_path }}/.env"
start_script: "{{ project_path }}/scripts/update_ngrok_url.sh"
