- name: Create kafka directory
  become: true
  file:
    path: /opt/dearlavion/kafka
    state: directory
    mode: '0755'

- name: Copy Kafka docker compose
  become: true
  template:
    src: docker-compose.kafka.yml.j2
    dest: /opt/dearlavion/kafka/docker-compose.yml

- name: Start Kafka and AKHQ
  become: true
  command: docker compose up -d
  args:
    chdir: /opt/dearlavion/kafka