---
- name: Run roles for the n8n project
  hosts: all
  vars:
    some_variable: "example"
  tasks:
    - name: Display current environment variables
      debug:
        msg:
          - "Environment: {{ env_name }}"
          - "Redis Host: {{ redis_host }}"
          - "Ngrok URL: {{ ngrok_url }}"

  roles:
    - docker
    - app
