- name: Ensure Docker Registry login
  include_role:
    name: docker_registry

- name: Remove API Gateway container (force redeploy)
  community.docker.docker_container:
    name: dearlavion-gateway-service
    state: absent
    force_kill: yes

- name: Pull and run API Gateway
  community.docker.docker_container:
    name: dearlavion-gateway-service
    image: "{{ gateway_image }}"
    pull: yes
    state: started
    restart_policy: always
    networks:
      - name: "{{ dearlavion_network }}"
    expose:
      - "{{ gateway_internal_port }}"
    env:
      auth_port: "{{ auth_port | string }}"
      core_port: "{{ core_port | string }}"
      notification_port: "{{ notification_port | string }}"
      media_port: "{{ media_port | string }}"