- name: Ensure Docker Registry login
  include_role:
    name: docker_registry

- name: Remove API Gateway container (force redeploy)
  community.docker.docker_container:
    name: dearlavion-gateway-service
    state: absent
    force_kill: yes

- name: Pull and run API Gateway
  community.docker.docker_container:
    name: dearlavion-gateway-service
    image: "{{ gateway_image }}"
    pull: yes
    state: started
    restart_policy: always
    networks:
      - name: "{{ dearlavion_network }}"
    expose:
      - "{{ gateway_internal_port }}"
    env:
      MEDIA_PORT: "{{ media_port | string }}"
      AUTH_PORT: "{{ auth_port | string }}"
      CORE_PORT: "{{ core_port | string }}"
      NOTIFICATION_PORT: "{{ notification_port | string }}"
      AKHQ_PORT: "{{ akhq_port | string }}"