- name: Ensure Docker Registry login
  include_role:
    name: docker_registry

- name: Remove API Gateway container (force redeploy)
  community.docker.docker_container:
    name: dearlavion-api-gateway
    state: absent
    force_kill: yes

- name: Pull and run API Gateway
  community.docker.docker_container:
    name: dearlavion-api-gateway
    image: "{{ api_gateway_image }}"
    pull: yes
    state: started
    restart_policy: always
    networks:
      - name: dearlavion-net
    expose:
      - "{{ api_gateway_internal_port }}"
    env:
      auth_port: "{{ auth_port }}"
      core_port: "{{ core_port }}"
      notification_port: "{{ notification_port }}"
      akhq_port: "{{ akhq_port }}"