# infra-deploy.yml
name: Deploy Infrastructure (DEV)

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component to deploy"
        required: true
        type: choice
        options:
          - akhq
          - nginx
          - redis
          - certificate
          - kafka
          - minio
          - all
      env:
        default: dev

jobs:
  deploy:
    uses: ./.github/workflows/common-ansible.yml
    with:
      target: ${{ inputs.component }}
      env: ${{ inputs.env }}
    secrets: inherit
